- name: Remote Desktop
  hosts: node_1 #, localhost
  vars:
    Destkop_Sharing: true
    Remote_Login: false
  roles:
    - dev/ansible-role-Gnome-Remote-Desktop

#- name: Thin Client
#  hosts: node_1
#  roles:
#    - dev/Gnome-Remote-Desktop-Connection
